Feature/htmltag databinding
viur-framework/viur-html5 pull request #17
Opened 2020-07-01 10:18 UTC by XeoN-GHMB

html tags can now have arguments preceded by a colon. These arguments are used for databinding.

i.e.:

self.skel = skelObj
self.structure = skelStructureObj

self.appendChild( '''
	<viurForm [name]="testform" :askel="skel" :astructure="structure">
''')

skelObj and skelStructureObj are now available in viurForm-Tag with name askel and astructure

2020-07-02 09:35 UTC, phorward commented
Hello @XeoN-GHMB,

I don't understand the use-case for this extension. Please provide more information what the purpose is.

On the first view, I thought that when I express say `<div [name]="test" :value="Hello World">`, I can access  `"Hello World"` by calling `self.name.value`, but the code works different and seems to connect values that need to be defined in the binder with the created objects. The binder can also be None, which is the case when you directly run `html5.fromHTML`. this will raise an exception, same as when the binder does not provide the specified attribute.

First of all, please provide a detailed explanation of the use case. Then we can discuss about further changes which may satisfy both my expectation and your requirement.

2020-07-02 09:37 UTC, phorward requested changes
Please describe your use-case and achievement more precisely.

2020-07-02 09:37 UTC, phorward commented on core.py
> +					refObj = getattr(bindTo, attrVal)
Exception raises here when both bindTo is None or attrVal is not found.

2020-07-03 11:17 UTC, sveneberth requested changes
Like @phorward I not understood the use-case. Can you explain why you need to bind these methods and where you want to call/access them?

2020-07-13 23:41 UTC, phorward commented
After a discussion at a local meeting, the following decisions had been made:

- this ":"-notation is valid and useful: It helps to pass through objects from the binder to subsequent objects
- anyway, it should also be possible to set attributes via just the identifier. In case there is a `_set<Attr>()` function available, this is called with the provided value, otherwise, a direct attribute with the identifier is set inside the Widget when id doesn't exist.
- We may think about a @-syntax used for events later on.

2020-07-13 23:43 UTC, phorward commented on core.py
> +					refObj = getattr(bindTo, attrVal)
@XeoN-GHMB please fix this to `refObj = getattr(bindTo, attrVal, None)` or add a valid error handling in case the attribute doesn't exist.

2020-07-17 13:51 UTC, phorward approved these changes

2020-07-17 13:51 UTC, merged